research_task:
  description: >
    Search the latest news and competitors of {topic}.
    The current date and time is {date}.
  expected_output: >
    A list of new articles about {topic} with the title, url, and snippet of the article.
  agent: researcher

reporting_task:
  description: >
    Review the context you have been given.
    Make sure the report is detailed and contains all relevant information.
  expected_output: >
    A detailed report of the new articles.
    The report should be in markdown format.
  agent: reporting_analyst
